title: KomuraSoft
description: Windowsアプリケーション開発を中心とした受託開発サービス
url: https://comcomponent.com
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude from build
exclude:
  - README.md
  - CNAME

# Permalink for posts
permalink: /blog/:year/:month/:day/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
