title: KomuraSoft
description: Windowsアプリケーション開発を中心とした受託開発サービス
url: https://comcomponent.com
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
future: true

include:
  - .well-known

# Exclude from build
exclude:
  - README.md
  - CNAME
  - docs

# Permalink for posts
permalink: /blog/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
